apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -hinco

labels:
  - pairs:
      app: hinco-wedding-frontend-hinco

patches:
  - target:
      kind: Service
      name: hinco-wedding-frontend
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30081
      - op: replace
        path: /spec/selector/app
        value: hinco-wedding-frontend-hinco
  - target:
      kind: Deployment
      name: hinco-wedding-frontend
    patch: |-
      - op: replace
        path: /spec/selector/matchLabels/app
        value: hinco-wedding-frontend-hinco
      - op: replace
        path: /spec/template/metadata/labels/app
        value: hinco-wedding-frontend-hinco

images:
  - name: ghcr.io/hinco114/hinco-wedding
    newTag: hinco-v2.0.0

